Booster implementation
PTS3-S34A/Library pull request #11
Opened 2016-12-07 14:48 UTC by marcgroos

2016-12-08 09:13 UTC, Ranray requested changes

2016-12-08 09:13 UTC, Ranray commented on Soccar [Library]/src/nl/soccar/library/ScoreBoard.java
> + * @author Robin Laugs
@author **PTS34A**

2016-12-08 14:04 UTC, BeeHiveJava commented
retest this please

2016-12-08 14:04 UTC, TehMessiah commented
SonarQube analysis reported 1 issue

Note: The following issues were found on lines that were not modified in the pull request. Because these issues can't be reported as line comments, they are summarized here:

1. ![MINOR](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/severity-minor.png) [ThrottleAction.java#L24](https://github.com/PTS3-S34A/Library/blob/38a9e6666f2d1c55ae332efe27ca85b2258375bd/Soccar [Library]/src/nl/soccar/library/enumeration/ThrottleAction.java#L24): Document this public method. [![rule](https://raw.githubusercontent.com/SonarCommunity/sonar-github/master/images/rule.png)](http://194.135.91.67:9000/coding_rules#rule_key=squid%3AUndocumentedApi)

2016-12-09 09:54 UTC, Ranray approved these changes

2016-12-09 09:55 UTC, merged